Added check for null return when creating package to fail the deploy when timing out

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -69,6 +69,10 @@ steps:
       echo "Error when creating package"
       exit 101
     fi
+    if [ "$packageVersionId" == "null" ]; then
+      echo "Error when creating package"
+      exit 101
+    fi
     echo "$packageVersionId" > $(Build.ArtifactStagingDirectory)/package-version.txt
     echo "$(INSTALLATION_KEY)" > $(Build.ArtifactStagingDirectory)/package-key.txt
   displayName: 'Create Package Version'
