Removed creation of package version

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -83,19 +83,19 @@ steps:
     testResultsFiles: '$(Common.TestResultsDirectory)/test-*-junit.xml'
     failTaskOnFailedTests: true
 
-- script: |
-    packageVersionId="`sfdx force:package:version:create --package "SAS Core" --installationkey "$(INSTALLATION_KEY)" --definitionfile config/project-scratch-def.json --wait 10 --json | jq '.result.SubscriberPackageVersionId' | tr -cd '[a-zA-Z0-9]'`"
-    if [ -z "$packageVersionId" ]; then
-      echo "Error when creating package"
-      exit 101
-    fi
-    if [ "$packageVersionId" == "null" ]; then
-      echo "Error when creating package"
-      exit 101
-    fi
-    echo "$packageVersionId" > $(Build.ArtifactStagingDirectory)/package-version.txt
-    echo "$(INSTALLATION_KEY)" > $(Build.ArtifactStagingDirectory)/package-key.txt
-  displayName: 'Create Package Version'
+#- script: |
+#    packageVersionId="`sfdx force:package:version:create --package "SAS Core" --installationkey "$(INSTALLATION_KEY)" --definitionfile config/project-scratch-def.json --wait 10 --json | jq '.result.SubscriberPackageVersionId' | tr -cd '[a-zA-Z0-9]'`"
+#    if [ -z "$packageVersionId" ]; then
+#      echo "Error when creating package"
+#      exit 101
+#    fi
+#    if [ "$packageVersionId" == "null" ]; then
+#      echo "Error when creating package"
+#      exit 101
+#    fi
+#    echo "$packageVersionId" > $(Build.ArtifactStagingDirectory)/package-version.txt
+#    echo "$(INSTALLATION_KEY)" > $(Build.ArtifactStagingDirectory)/package-key.txt
+#  displayName: 'Create Package Version'
 
 - script: |
     sfdx force:source:convert --rootdir ./sas-core --outputdir ./package-md
